### ISSUE TITLE
Example of multi-modal use?

### ISSUE THREAD

**Issue by ikmolbo** [derrickobedgiu1/gemini-api#1]
Thanks a lot for your work on this. It looks really comprehensive. 

Can you add an example of how to use this with an image or PDF, both via base64 and file upload methods?

**Comment by derrickobedgiu1** [comment]
Glad you found the library useful. Am hoping #2 solves all your queries?

**Comment by ikmolbo** [comment]
Wow, that's outstandingly good. Thank you.

I feel like I'm asking a lot, but do you plan to implement the [Gemini API Files upload](https://ai.google.dev/api/files) here too?

**Comment by derrickobedgiu1** [comment]
The Files API is already available. Files are uploaded via [Media Resource](https://github.com/derrickobedgiu1/gemini-api?tab=readme-ov-file#media-resource)  and managed via [File Resource](https://github.com/derrickobedgiu1/gemini-api?tab=readme-ov-file#file-resource). The library uses naming from this link: https://ai.google.dev/api/all-methods
